### ISSUE TITLE
how to set app.use  express.bodyparse in krakenjs

### ISSUE THREAD

**Issue by kazuki-tu** [lmarkus/Kraken_Example_Shopping_Cart#15]
i want't to use  to set upload ,where set this conf in krakenjs ?

 app.use(express.bodyParser({ 
    keepExtensions: true, 
    uploadDir: __dirname + '/tmp',
    limit: '2mb'
  }));

is it in app.json?

{
    "port": ["OPENSHIFT_NODEJS_PORT", "VCAP_APP_PORT", "PORT", 8001],

```
"databaseConfig": {
    "host": "localhost",
    "database": "ucrm"
},

"bcrypt": {
    "difficulty": 8
},

"express" : {
    "trust proxy" : true,
    "bodyParser" : {
        "keepExtension":true,
        "limit": "1kb"
    }
}
```

}

it seems less effective ....

**Comment by lmarkus** [comment]
Hi, these examples have been deprecated.
Please take a look at the new ones in the krakenjs repo  :)
