### ISSUE TITLE
a question about security

### ISSUE THREAD

**Issue by mgenev** [lmarkus/Kraken_Example_Shopping_Cart#2]
Hi,

great job putting this together. It is very simplistic and useful and well described. I think I understand almost everything. 

I have a question about security, I went over the usage of kraken's web security lib lisca and understand what it does, my question is besides that and utilizing the paypal SDK, do I need to worry about running a SSL/TLS type of server for requests or is the current level of security sufficient? 

I do see a reference to the TLS part of node in the kraken docs, but no usage of it in this shopping cart example.

If I do need extra security through ssl, when is it appropriate to start using it in the app flow if I don't plan to make it mandatory for users to be logged in.

Thank you and again, great job, I'm very happy and will use this for sure in my software,
Martin

**Comment by lmarkus** [comment]
Hi @mgenev,
Thanks for the comments.

Yes, you absolutely need to run this over SSL.  This example focused on the functionality more than the infrastructure surrounding the project. This features a form that POST's credit card numbers to the server, so it should (at a bare minimum) be encrypted.

If you don't want to handle credit card numbers directly,  I'm working on a pure PayPal variant of this example (Hopefully by Friday).
In this case, the customer is redirected to PayPal, where the payment will be processed before being returned to your site.

**Comment by mgenev** [comment]
Thanks for the quick response, right, I noticed the card part and wondered about that. I currently use the 2nd approach in the php carts and plugins I use for my clients, but am redoing everything in Node and will be excited to see your implementation. With the 2nd variant, does the SSL protected part kick in once the user is redirected to paypal, thus freeing me from the need to build it into my app? I think that's how my php carts do it...

**Comment by lmarkus** [comment]
Correct,
The customer is redirected to a secure checkout page, hosted by PayPal. After PayPal has collected the relevant information, and executed the payment, the customer is sent back to your site along with a confirmation of payment.

**Comment by mgenev** [comment]
excellent, this would be my preferred approach, i'm looking forward to the next example, meanwhile i will start re-tailoring my prototype to work within kraken

**Comment by mgenev** [comment]
this is really cool btw :) 
// Identify credit card type. Patent pending. Credit cards starting with 3 = amex, 4 = visa, 5 = mc , 6 = discover
var ccType = (['amex','visa','mastercard','discover'])[parseInt(cc.slice(0,1),10)-3];

**Comment by lmarkus** [comment]
:smile:
