### ISSUE TITLE
Is possible to use session with redis?

### ISSUE THREAD

**Issue by h4ckm03d** [lmarkus/Kraken_Example_Shopping_Cart#5]
Current example is using memory session, can I use connect-redis instead of memory?
If possible using connect-redis, may I know how to put session-redis configuration.

Thanks.

**Comment by alexsantos** [comment]
I managed to use Mongo as I didn't want to install another DB, but with a few changes you can use Redis instead. Here is what I've done, after digging the source code for kraken session.js

In the middleware.js file, change the session entry to this:

```
  "session": {
      "module": "connect-mongo",
      "config": {
        "db": "test"
      },
      "secret": "80bc6d67f80813ccc78ff77adf0eefcafa7eeef6"
  }
```

And that's it! Simple.

**Comment by lmarkus** [comment]
Alex was kind enough to post a great example of this:
https://github.com/AlexSantos/Kraken_Example_Session_Redis

**Comment by h4ckm03d** [comment]
Great example, thanks Alex.
