### ISSUE TITLE
yo kraken:locale index ES es - should auto create the keys of the origin file into the destination contentFile

### ISSUE THREAD

**Issue by athahar** [lmarkus/Kraken_Example_Shopping_Cart#6]
A nice to have feature.
yo kraken:locale index ES es - should auto create the keys of the origin file into the destination contentFile instead of the current default "greetings" key.

I can create an enhancement request against the main krakenjs repo, if you would like.

**Comment by lmarkus** [comment]
Hi @athahar ,
Yes, if you don't mind, could you submit a PR against https://github.com/paypal/generator-kraken/

Thanks!
