### ISSUE TITLE
connect vs express

### ISSUE THREAD

**Issue by alexsantos** [lmarkus/Kraken_Example_Shopping_Cart#8]
On the Controller paragraph you mention the need to use the express' methodOverride() middleware and then you add a link to the documentation, but that's a Connect middleware. I instead added

```
connect = require('connect'),
```

and then

```
server.use(connect.methodOverride());
```

**Comment by lmarkus** [comment]
Hi Alex,
express exposes connect's middleware.
I decided to use `express.methodOverride()` to keep the code a bit cleaner.  (Since in other examples, I was already including express for other reasons)

Your code should work exactly the same.
